version: '3.8'

services:
  chatbot:
    container_name: katIA
    build: 
      context: ./chatbot
    depends_on:
      - pgvector
    restart: always
    ports:
      - '$PORT:$PORT'
    env_file:
      - .env
    volumes:
      - ./chatbot:/app
    environment:
      LLM: $LLM                             # Language model to use
      LLM_SERVER: $LLM_SERVER               # Endpoint URL for the llm service
      LLM_PORT: $LLM_PORT                   # Port for the the llm service
      PORT: $PORT                           # Port for the frontend
      PG_HOST: $PG_HOST                     # Hostname of the PostgreSQL service
      PG_PORT: $PG_PORT                     # PostgreSQL port
      PG_USER: $PG_USER                     # PostgreSQL user
      PG_PASSWORD: $PG_PASSWORD             # PostgreSQL password
      PG_DB: $PG_DB                         # PostgreSQL database
    extra_hosts:
      - "$LLM_SERVER:host-gateway"          # ONLY if running ollama locally
    networks:
      - katia

  pgvector:
    container_name: $PG_HOST
    image: ankane/pgvector
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
    restart: always
    ports:
      - "$PG_PORT:$PG_PORT"
    #volumes:
    #  - pgdata:/var/lib/postgresql/data
    networks:
      - katia

networks:
  katia:
    driver: bridge

#volumes:
#  pgdata:
#    driver: local
